[web]
development = true
address = "testing-nuke.gl.at.ply.gg"
port = 443
ports = [53422]
loginUrl = "grow.cenitdigital.cl"
cdnUrl = "http://cdn.cenitdigital.cl"

[web.maintenance]
enable = false
message = "Maintenance Woi"

[web.tls]
key = "./assets/ssl/server.key"
cert = "./assets/ssl/server.crt"

[webFrontend]
root = "./.cache/website"
port = 8080

[webFrontend.tls]
key = "./.cache/ssl/_wildcard.growserver.app-key.pem"
cert = "./.cache/ssl/_wildcard.growserver.app.pem"

[server]
bypassVersionCheck = true
logLevel = "debug"